### ISSUE TITLE
Feature request: Add an option to disable SSL verification

### ISSUE THREAD

**Issue by numo68** [drygdryg/netbox-device-autodiscovery#8]
Hello,

I am learning netbox and playing with various scripts and tools. My environment uses self-signed certificates, including the host running the netbox. Unfortunately I did not found any configuration to either disable the verification, or to specify the trusted CA. An attempt to run the discovery immediately fails with
```
2022-03-03 22:15:50,367 {/netbox-device-autodiscovery/./run.py:70} [INFO] Verifying all prerequisite objects exist in NetBox.
Traceback (most recent call last):
   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
     httplib_response = self._make_request(
   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
     self._validate_conn(conn)
   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
     conn.connect()
   File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 416, in connect
     self.sock = ssl_wrap_socket(
   File "/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
     ssl_sock = _ssl_wrap_socket_impl(
   File "/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
   File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
     return self.sslsocket_class._create(
   File "/usr/lib/python3.9/ssl.py", line 1040, in _create
     self.do_handshake()
   File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
     self._sslobj.do_handshake()
 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 440, in send
     resp = conn.urlopen(
   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
   File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 592, in increment
     raise MaxRetryError(_pool, url, error or ResponseError(cause))
 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='netbox.meduna.lan', port=443): Max retries exceeded with url: /api/dcim/device-roles/?name=PC&limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
 
During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/netbox-device-autodiscovery/./run.py", line 285, in <module>
     main()
   File "/netbox-device-autodiscovery/./run.py", line 211, in main
     verify_prerequisites()
   File "/netbox-device-autodiscovery/./run.py", line 76, in verify_prerequisites
     create_or_update_nb_obj(requirement_type, requirement)
   File "/netbox-device-autodiscovery/./run.py", line 147, in create_or_update_nb_obj
     existing_nb_obj = getattr(getattr(nb, api_app), api_model).get(**query_params)
   File "/usr/local/lib/python3.9/dist-packages/pynetbox/core/endpoint.py", line 148, in get
     ret = next(resp, None)
   File "/usr/local/lib/python3.9/dist-packages/pynetbox/core/response.py", line 117, in __next__
     next(self.response), self.endpoint.api, self.endpoint
   File "/usr/local/lib/python3.9/dist-packages/pynetbox/core/query.py", line 321, in get
     req = self._make_call(add_params=add_params)
   File "/usr/local/lib/python3.9/dist-packages/pynetbox/core/query.py", line 271, in _make_call
     req = getattr(self.http_session, verb)(
   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 542, in get
     return self.request('GET', url, **kwargs)
   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 529, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 645, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 517, in send
     raise SSLError(e, request=request)
 requests.exceptions.SSLError: HTTPSConnectionPool(host='XXXXX', port=443): Max retries exceeded with url: /api/dcim/device-roles/?name=PC&limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

I don't know the relevant libraries but from some googling it seems that pynetbox can be persuaded to disable the verification.

Thanks

**Comment by drygdryg** [comment]
Implemented: https://github.com/drygdryg/netbox-device-autodiscovery/commit/aec08bb6092af82810c3b0ec065dece8dd45d53d
Please check it and write

**Comment by numo68** [comment]
Wow, that was quick :) Works for contacting the netbox when checking the prerequisites but fails for the nmap scanner module

```
2022-03-04 09:30:37,877 {/netbox-device-autodiscovery/run.py:78} [INFO] Finished verifying prerequisites.
2022-03-04 09:30:37,877 {/netbox-device-autodiscovery/run.py:219} [INFO] Running module "nmap_network_scanner"…
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='XXXXX', port=443): Max retries exceeded with url: /api/extras/tags/?slug=do-not-autodiscover&limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/netbox-device-autodiscovery/run.py", line 286, in <module>
    main()
  File "/netbox-device-autodiscovery/run.py", line 224, in main
    nb_objects = m.run()
  File "/netbox-device-autodiscovery/modules/nmap_network_scanner/nmap_network_scanner.py", line 55, in run
    autodiscovery_disabled_tag = nb.extras.tags.get(slug='do-not-autodiscover')
  File "/usr/local/lib/python3.9/dist-packages/pynetbox/core/endpoint.py", line 148, in get
    ret = next(resp, None)
  File "/usr/local/lib/python3.9/dist-packages/pynetbox/core/response.py", line 117, in __next__
    next(self.response), self.endpoint.api, self.endpoint
  File "/usr/local/lib/python3.9/dist-packages/pynetbox/core/query.py", line 321, in get
    req = self._make_call(add_params=add_params)
  File "/usr/local/lib/python3.9/dist-packages/pynetbox/core/query.py", line 271, in _make_call
    req = getattr(self.http_session, verb)(
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='XXXXX', port=443): Max retries exceeded with url: /api/extras/tags/?slug=do-not-autodiscover&limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

**Comment by drygdryg** [comment]
> Wow, that was quick :) Works for contacting the netbox when checking the prerequisites but fails for the nmap scanner module

Fixed in https://github.com/drygdryg/netbox-device-autodiscovery/commit/9f5a86d857f6b10cd935272c27109076544592fd
Please check it and write back.

**Comment by numo68** [comment]
I tested both disabling and providing a CA PEM, both work. Thanks!
